#
# Copyright 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0
#

# I believe I need to add this so tha the extension is activated at runtime?
quarkus:
  log:
    handler:
      kafka:
        enabled: ${KAFKA_LOG_ENABLED:false}
        broker-list: ${KAFKA_LOG_SERVER:kafka.example.com:443}
        topic: ${KAFKA_LOG_TOPIC:kafka-topic}
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-512
        sasl-jaas-conf: "${sasl_jaas_conf}"
        filter-logger-name-pattern: ${KAFKA_LOG_FILTER:org.jboss.pnc.*}
        level: INFO
        # set this to empty because default config set the wrong path
        ssl-truststore-location: ""
  oidc:
    auth-server-url: https://keycloak-host/auth/realms/myrealm
    client-id: client
    credentials:
      secret: secret
    tls:
      verification: none
  oidc-client:
    auth-server-url: http://localhost:8180/auth/realms/quarkus/
    client-id: my-app
    credentials:
      secret: secret
  fault-tolerance:
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/findBrewBuildOfNVR":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
        abort-on: "org.jboss.pnc.causeway.CausewayFailure"
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/findBrewBuild":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
        abort-on: "org.jboss.pnc.causeway.CausewayFailure"
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/tagBuild":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
        abort-on: "org.jboss.pnc.causeway.CausewayFailure"
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/isBuildTagged":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/untagBuild":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
        abort-on: "org.jboss.pnc.causeway.CausewayFailure"
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/importBuild":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
        abort-on: "org.jboss.pnc.causeway.CausewayFailure"
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.brewclient.BrewClientImpl/tagsExists":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.pncclient.PncClientImpl/findBuild":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.pncclient.PncClientImpl/getBuildLog":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.pncclient.PncClientImpl/getAlignLog":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.pncclient.PncClientImpl/getSources":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}
    "org.jboss.pnc.causeway.pncclient.PncClientImpl/findBuildArtifacts":
      retry:
        max-retries: ${fault-tolerance.max-retry}
        delay: ${fault-tolerance.delay}
      exponential-backoff:
        factor: ${fault-tolerance.factor}


fault-tolerance:
  max-retry: 4
  delay: 1000
  factor: 4

causeway:
  koji:

  pnc:
    builds-url: ${causeway.pnc.url}/../pnc-web/builds/
    system-version: 3

"%dev":
  quarkus:
    log:
      category:
        "org.jboss.pnc":
          level: DEBUG
        "org.commonjava.util.jhttpc.INTERNAL.conn":
          level: WARN
  causeway:
    koji:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/kojihub"
      web-url: "http://localhost:${quarkus.wiremock.devservices.port}/koji/buildinfo?buildID="
      client-key-certificate-file: src/test/resources/cert/snakeoil.pem
      client-certificate-password: password
#      server-certificate-file: src/test/resources/cert/snakeoil.pem
    pnc:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/pnc-rest/rest"


"%test":
  causeway:
    koji:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/kojihub"
      web-url: "http://localhost:${quarkus.wiremock.devservices.port}/koji/buildinfo?buildID="
      client-key-certificate-file: src/test/resources/cert/snakeoil.pem
      client-certificate-password: password
    #      server-certificate-file: src/test/resources/cert/snakeoil.pem
    pnc:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/pnc-rest/rest"
  quarkus:
    oidc:
      enabled: false
    oidc-client:
      enabled: false
