#
# Copyright 2024 Red Hat, Inc.
# SPDX-License-Identifier: Apache-2.0
#

# I believe I need to add this so tha the extension is activated at runtime?
quarkus:
  oidc:
    auth-server-url: https://keycloak-host/auth/realms/myrealm
    client-id: client
    credentials:
      secret: secret
    tls:
      verification: none
  oidc-client:
    auth-server-url: http://localhost:8180/auth/realms/quarkus/
    client-id: my-app
    credentials:
      secret: secret

causeway:
  koji:

  pnc:
    builds-url: ${causeway.pnc.url}/../pnc-web/builds/
    system-version: 3

"%dev":
  quarkus:
    log:
      category:
        "org.jboss.pnc":
          level: DEBUG
        "org.commonjava.util.jhttpc.INTERNAL.conn":
          level: WARN
  causeway:
    koji:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/kojihub"
      web-url: "http://localhost:${quarkus.wiremock.devservices.port}/koji/buildinfo?buildID="
      client-key-certificate-file: src/test/resources/cert/snakeoil.pem
      client-certificate-password: password
#      server-certificate-file: src/test/resources/cert/snakeoil.pem
    pnc:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/pnc-rest/rest"


"%test":
  causeway:
    koji:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/kojihub"
      web-url: "http://localhost:${quarkus.wiremock.devservices.port}/koji/buildinfo?buildID="
      client-key-certificate-file: src/test/resources/cert/snakeoil.pem
      client-certificate-password: password
    #      server-certificate-file: src/test/resources/cert/snakeoil.pem
    pnc:
      url: "http://localhost:${quarkus.wiremock.devservices.port}/pnc-rest/rest"
